# Generated by Django 6.0.5 on 2026-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedaffiliatelink',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackedaffiliatelink',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
