# Generated by Django 6.0.5 on 2026-06-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_trackedaffiliatelink_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedaffiliatelink',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
