# Generated by Django 6.0.5 on 2026-06-16 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_trackedaffiliatelink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateclick',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='affiliate.trackedaffiliatelink'),
        ),
    ]
