services:
  web:
    build: .
    container_name: humrine_site_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    networks:
      - humrine-network

networks:
  humrine-network:
    driver: bridge
