# Generated by Django 6.0.5 on 2026-06-27 16:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toonstory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
